#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Insider Tracker — Hetzner CX22 Deployment Script
#
# Run this ONCE on a fresh Ubuntu 24.04 server to set everything up.
#
# Usage:
#   ssh root@YOUR_SERVER_IP
#   curl -fsSL https://raw.githubusercontent.com/YOUR_USERNAME/Insider-Tracker/main/scripts/deploy.sh | bash
#
# Or copy manually:
#   scp scripts/deploy.sh root@YOUR_SERVER_IP:/root/
#   ssh root@YOUR_SERVER_IP bash /root/deploy.sh
#
# What this does:
#   1. Updates system packages
#   2. Installs Node.js 20, npm, git
#   3. Installs Chromium (for future Puppeteer scrapers)
#   4. Creates /opt/insider-tracker with correct permissions
#   5. Clones the GitHub repo
#   6. Installs npm dependencies
#   7. Creates .env from your input
#   8. Sets up the daily cron job
#   9. Runs the scraper once to verify everything works
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Config — edit these before running ───────────────────────────────────────

GITHUB_REPO="https://github.com/YOUR_USERNAME/Insider-Tracker.git"   # ← change this
APP_DIR="/opt/insider-tracker"
APP_USER="insider"          # dedicated system user (not root)
CRON_SCHEDULE="0 22 * * *" # 22:00 UTC = 23:00 CET

# ─────────────────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[deploy]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC}   $*"; }
err()  { echo -e "${RED}[error]${NC}  $*" >&2; exit 1; }

# Must run as root
if [ "$(id -u)" -ne 0 ]; then
  err "Run this script as root (ssh root@your-server)"
fi

log "Starting Insider Tracker deployment on $(hostname)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── 1. System update ─────────────────────────────────────────────────────────

log "Updating system packages…"
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl git unzip

# ── 2. Node.js 20 ────────────────────────────────────────────────────────────

if ! command -v node &>/dev/null || [[ "$(node --version)" != v20* ]]; then
  log "Installing Node.js 20…"
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
else
  log "Node.js $(node --version) already installed — skipping"
fi

log "Node: $(node --version) | npm: $(npm --version)"

# ── 3. Chromium (for Puppeteer scrapers) ─────────────────────────────────────

log "Installing Chromium and dependencies…"
apt-get install -y -qq \
  chromium-browser \
  fonts-liberation \
  libappindicator3-1 \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libdbus-1-3 \
  libgbm1 \
  libgtk-3-0 \
  libnspr4 \
  libnss3 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  xdg-utils 2>/dev/null || warn "Some Chromium deps skipped (may already be installed)"

CHROMIUM_PATH="$(which chromium-browser 2>/dev/null || which chromium 2>/dev/null || echo '')"
if [ -z "$CHROMIUM_PATH" ]; then
  warn "Chromium not found in PATH — Puppeteer scrapers will need manual configuration"
else
  log "Chromium: $CHROMIUM_PATH ($(chromium-browser --version 2>/dev/null || chromium --version))"
fi

# ── 4. Create dedicated system user ──────────────────────────────────────────

if ! id "$APP_USER" &>/dev/null; then
  log "Creating system user '$APP_USER'…"
  useradd --system --shell /bin/bash --home-dir "$APP_DIR" --create-home "$APP_USER"
else
  log "User '$APP_USER' already exists — skipping"
fi

# ── 5. Clone repository ───────────────────────────────────────────────────────

if [ -d "$APP_DIR/.git" ]; then
  log "Repo already cloned — pulling latest…"
  sudo -u "$APP_USER" git -C "$APP_DIR" pull --ff-only
else
  log "Cloning repo into $APP_DIR…"
  rm -rf "$APP_DIR"
  git clone "$GITHUB_REPO" "$APP_DIR"
  chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
fi

# ── 6. Install npm dependencies ───────────────────────────────────────────────

log "Installing npm dependencies…"
cd "$APP_DIR"
sudo -u "$APP_USER" npm ci --omit=dev --silent

# ── 7. Create .env ────────────────────────────────────────────────────────────

if [ -f "$APP_DIR/.env" ]; then
  warn ".env already exists — skipping (delete it manually if you want to reconfigure)"
else
  log "Configuring environment variables…"
  echo ""
  echo "  Enter your Supabase credentials."
  echo "  (Find these in your Supabase project → Settings → API)"
  echo ""

  read -rp "  SUPABASE_URL (https://xxxx.supabase.co): " SUPABASE_URL
  read -rp "  SUPABASE_KEY (service_role key):         " SUPABASE_KEY

  cat > "$APP_DIR/.env" <<EOF
# Insider Tracker — Environment Variables
# Generated by deploy.sh on $(date -u '+%Y-%m-%d %H:%M UTC')

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_KEY=${SUPABASE_KEY}
NODE_ENV=production

# Puppeteer — path to system Chromium (avoids downloading a second browser)
PUPPETEER_EXECUTABLE_PATH=${CHROMIUM_PATH:-/usr/bin/chromium-browser}
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
EOF

  chmod 600 "$APP_DIR/.env"
  chown "$APP_USER":"$APP_USER" "$APP_DIR/.env"
  log ".env created and locked to owner-only (chmod 600)"
fi

# ── 8. Make scripts executable ────────────────────────────────────────────────

chmod +x "$APP_DIR/scripts/run-daily.sh"
chmod +x "$APP_DIR/scripts/deploy.sh"
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"

# ── 9. Create log directory ───────────────────────────────────────────────────

mkdir -p "$APP_DIR/logs"
chown "$APP_USER":"$APP_USER" "$APP_DIR/logs"

# ── 10. Install cron job ──────────────────────────────────────────────────────

CRON_CMD="$CRON_SCHEDULE $APP_DIR/scripts/run-daily.sh"
CRONTAB_FILE="/etc/cron.d/insider-tracker"

log "Installing cron job: $CRON_CMD"
cat > "$CRONTAB_FILE" <<EOF
# Insider Tracker — Daily scrape at 23:00 CET (22:00 UTC)
# Managed by deploy.sh — do not edit manually
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

${CRON_SCHEDULE} ${APP_USER} ${APP_DIR}/scripts/run-daily.sh
EOF

chmod 644 "$CRONTAB_FILE"
log "Cron installed at $CRONTAB_FILE"

# ── 11. Test run ──────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "Running Germany scraper as smoke test…"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cd "$APP_DIR"

# Load .env for this test run
set -a
# shellcheck disable=SC1090,SC1091
source "$APP_DIR/.env"
set +a

sudo -E -u "$APP_USER" node run-all.js DE

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "Deployment complete!"
echo ""
echo "  App directory:  $APP_DIR"
echo "  Cron schedule:  $CRON_SCHEDULE (22:00 UTC = 23:00 CET)"
echo "  Log directory:  $APP_DIR/logs/"
echo "  Run manually:   sudo -u $APP_USER $APP_DIR/scripts/run-daily.sh"
echo "  Test one market: cd $APP_DIR && node run-all.js DE"
echo "  View logs:       tail -f $APP_DIR/logs/scrape-\$(date +%Y-%m-%d).log"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
